# Generated by Django 5.1.5 on 2025-01-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='created_at',
        ),
        migrations.AddField(
            model_name='target',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
